name: map_challenge
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  google_maps_flutter: ^2.10.0
  lottie: ^3.1.3
  flutter_expandable_fab: ^2.3.0
  permission_handler: ^11.3.1
  custom_map_markers: ^0.0.2+1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  location: ^7.0.1
  animate_do: ^3.3.4
  animated_icon: ^0.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/



  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
